version = 1

test_patterns = [
  "tests/**"
]

exclude_patterns = [
  "tools/**",
  "examples/**",
  "docs/**"
]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"
