repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v6.0.0"
    hooks:
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-toml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.15.8"
    hooks:
      - id: ruff-format
        args: [--config=pyproject.toml]
      - id: ruff-check
        args: [--config=pyproject.toml, --fix, --exit-non-zero-on-fix]

  - repo: https://github.com/crate-ci/typos
    rev: v1.44.0
    hooks:
      - id: typos
        exclude: |
          (?x)^(
            tests/.*
          )$
